# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test Application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
    - name: Build
      run: go build -v -o kozukai ./cmd
    - name: Generate the iconlist
      run: go run . generate
    - name: Test
      run: go test -v -coverprofile cover.out ./...